name: Nightly Build for kilted

on:
  schedule:
    - cron: '0 13 * * *'  # Runs every day at midnight, 13:00 UTC

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ros:kilted
      env:
        ROS_DISTRO: kilted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build and Test with ROS kilted
        shell: bash
        run: |
          ./scripts/build-verification.sh
