# This is workflow for parameter server with rolling
name: rolling

on:
  push:
    branches: [ "rolling" ]
  pull_request:
    branches: [ "rolling" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # each job goes for each ros supported distribution.
  # each job description absorb the distribution dependency as much as possible,
  # so that build verification script can be agnostic from distribution dependency.

  build:
    runs-on: ubuntu-latest
    container:
      image: ros:rolling
      env:
        ROS_DISTRO: rolling
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build with ROS rolling
        shell: bash
        run: |
          ./scripts/build-verification.sh
